include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
    - always_specify_types
    - avoid_dynamic_calls
    - avoid_print
    - avoid_returning_null
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_void_async
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - empty_statements
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_typing_uninitialized_variables
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_string_escapes
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
